# Jekyll Configuration
title: "Eric Liu — Portfolio"
description: "Personal website for Eric Liu :D"
baseurl: ""
url: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Collections
collections:
  projects:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
